title: Faishal Wafiq Zakiy, S.Kom., M.T.I.
description:  Resume atau riwayat hidup dari Faishal Wafiq Zakiy, S.Kom., M.T.I.
url: https://resume.zakiy.my.id
baseurl: ''
theme_skin: blue

sass:
  sass_dir: _sass
  style: compressed

plugins:
    - jekyll-minifier

exclude:
  - docker-compose.yml
